version: '3'

services:
  llmine_core_redis:
    image: redis:latest

  llmine_core_db:
    build:
      context: .
      dockerfile: ./Dockerfile.db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .sample.env

  llmine_core_celery:
    build: .
    entrypoint: /home/llmine_core/docker-entrypoint-celery.sh
    depends_on:
      - llmine_core_redis
      - llmine_core_db
    volumes:
      - static:/home/llmine_core/static/
      - media:/home/llmine_core/media/
    env_file:
      - .sample.env
  
  llmine_core:
    build: .
    entrypoint: /home/llmine_core/docker-entrypoint-gunicorn.sh
    depends_on:
      - llmine_core_celery
      - llmine_core_db
    volumes:
      - static:/home/llmine_core/static/
      - media:/home/llmine_core/media/
    env_file:
      - .sample.env

  llmine_core_nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/var/www-data/static/
    depends_on:
      - llmine_core


volumes:
  pgdata:
  static:
  media:
