# Use an official Python 3.10 runtime as the base image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt /app/

# Install Celery and any other necessary dependencies
# TODO: Need to add only required depedency
RUN pip install --no-cache-dir -r requirements.txt

# Copy your Celery application code into the container
COPY . /app/

ENV DJANGO_SETTINGS_MODULE=llmine_core.settings

# Set the command to run your Celery worker
CMD ["celery", "-A", "llmine_core", "worker", "--loglevel=info"]