# Generated by Django 4.2.2 on 2023-08-20 09:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("pool_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InjestedTextContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("content_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("text_content", models.TextField()),
                ("metadata_json", models.JSONField(blank=True, null=True)),
                (
                    "datasource_type_name",
                    models.CharField(
                        choices=[("standard", "standard")], max_length=255
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contentpool",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExtracterPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("prompt_name", models.CharField(max_length=100, unique=True)),
                ("prompt_text", models.TextField()),
                (
                    "return_type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("label", "label"),
                            ("json", "json"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "jsonschema",
                    models.TextField(
                        blank=True,
                        help_text="Only used when return type is json",
                        null=True,
                    ),
                ),
                (
                    "labels_config_json",
                    models.JSONField(
                        blank=True,
                        help_text="Only used when return type is label",
                        null=True,
                    ),
                ),
                (
                    "content_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contentpool",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
