# Generated by Django 4.2.2 on 2023-08-20 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datasources", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="injestedtextcontent",
            name="datasource_type_name",
        ),
        migrations.AddField(
            model_name="injestedtextcontent",
            name="datasource",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="datasources.datasource",
            ),
            preserve_default=False,
        ),
    ]
