# Generated by Django 4.2.2 on 2023-08-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_contentpool_llm_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extracterprompt",
            name="content_pool",
        ),
        migrations.CreateModel(
            name="ExtracterChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("chain_name", models.CharField(max_length=100, unique=True)),
                (
                    "content_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contentpool",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
