# Generated by Django 4.2.2 on 2023-08-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_injestedtextcontent_process_completed_successfully"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracterprompt",
            name="order_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracterprompt",
            name="run_if_expr",
            field=models.TextField(
                blank=True, help_text="Blank means always run", null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="extracterprompt",
            unique_together={("extracter_chain", "order_index")},
        ),
    ]
