# Generated by Django 4.2.2 on 2023-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_extracterprompt_order_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extracterprompt",
            name="order_index",
            field=models.IntegerField(default=0),
        ),
    ]
