# Generated by Django 4.2.2 on 2023-08-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_extracterprompt_order_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentpool",
            name="llm_name",
        ),
        migrations.AddField(
            model_name="extracterchain",
            name="llm_name",
            field=models.CharField(
                choices=[
                    ("gpt-3.5-turbo", "gpt-3.5-turbo"),
                    ("gpt-3.5-turbo-16k", "gpt-3.5-turbo-16k"),
                    ("gpt-4", "gpt-4"),
                ],
                default="gpt-3.5-turbo",
                max_length=255,
            ),
        ),
    ]
