# Generated by Django 4.2.2 on 2023-09-04 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_contentpool_llm_name_extracterchain_llm_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("export_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("export_type", models.CharField(max_length=255)),
                ("data_file", models.FileField(upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
