# Generated by Django 4.2.2 on 2023-08-19 17:28

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = []
    operations = [VectorExtension()]
